# Generated by Django 2.2.6 on 2019-11-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191101_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Element_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpectraSearchID', models.IntegerField(max_length=6)),
                ('Manufacturer', models.CharField(max_length=30)),
                ('CatalogNumber', models.CharField(max_length=20)),
                ('Descripthon', models.CharField(max_length=255)),
                ('DocumentCreator', models.CharField(max_length=30)),
                ('UniqueIdentifier', models.CharField(max_length=20)),
                ('MeasurementEquipment', models.CharField(max_length=20)),
                ('Laboratory', models.CharField(max_length=30)),
                ('ReportNumber', models.CharField(max_length=20)),
                ('ReportDate', models.DateTimeField()),
                ('DocumentCreationDate', models.DateTimeField()),
                ('Comments', models.CharField(max_length=255)),
            ],
        ),
    ]
