# Generated by Django 2.2.6 on 2019-11-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_header_element_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_element_fields',
            name='SpectraSearchID',
            field=models.IntegerField(),
        ),
    ]
