# Generated by Django 2.2.6 on 2019-11-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reflectiongeometry_spectral_data_spectral_distribution_fields_spectralquantity_transmissiongeometry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spectral_Data',
        ),
    ]
