# Generated by Django 2.2.6 on 2019-11-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_spectral_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectral_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpectraSearchID', models.IntegerField()),
                ('data_array_0', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
