# Generated by Django 2.2.6 on 2019-11-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_spectral_data_data_array_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_element_fields',
            name='SpectraSearchID',
        ),
        migrations.RemoveField(
            model_name='header_element_fields',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reflectiongeometry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spectral_data',
            name='SpectraSearchID',
        ),
        migrations.RemoveField(
            model_name='spectral_data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spectral_distribution_fields',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spectralquantity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transmissiongeometry',
            name='id',
        ),
        migrations.AddField(
            model_name='header_element_fields',
            name='SpectralSearchID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='spectral_data',
            name='SpectralSearchID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reflectiongeometry',
            name='GeoKey',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spectral_distribution_fields',
            name='SpectralSearchID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spectralquantity',
            name='SpectralQKey',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transmissiongeometry',
            name='TranKey',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
