# Generated by Django 2.2.6 on 2019-11-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191102_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header_Element_Fields',
        ),
        migrations.DeleteModel(
            name='ReflectionGeometry',
        ),
        migrations.DeleteModel(
            name='Spectral_Data',
        ),
        migrations.DeleteModel(
            name='Spectral_Distribution_Fields',
        ),
        migrations.DeleteModel(
            name='SpectralQuantity',
        ),
        migrations.DeleteModel(
            name='TransmissionGeometry',
        ),
    ]
