# Generated by Django 2.2.6 on 2019-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191102_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Element_Fields',
            fields=[
                ('SpectralSearchID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Manufacturer', models.CharField(max_length=30)),
                ('CatalogNumber', models.CharField(max_length=20)),
                ('Descripthon', models.CharField(max_length=255)),
                ('DocumentCreator', models.CharField(max_length=30)),
                ('UniqueIdentifier', models.CharField(max_length=20)),
                ('MeasurementEquipment', models.CharField(max_length=20)),
                ('Laboratory', models.CharField(max_length=30)),
                ('ReportNumber', models.CharField(max_length=20)),
                ('ReportDate', models.DateTimeField()),
                ('DocumentCreationDate', models.DateTimeField()),
                ('Comments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionGeometry',
            fields=[
                ('value', models.CharField(max_length=5)),
                ('GeoKey', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spectral_Data',
            fields=[
                ('SpectralSearchID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('data_array_0', models.DecimalField(decimal_places=2, max_digits=3)),
                ('data_array_1', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Spectral_Distribution_Fields',
            fields=[
                ('SpectralSearchID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('SpectralQuantity', models.CharField(max_length=13)),
                ('ReflectionGeometry', models.CharField(max_length=5)),
                ('TransmissionGeometry', models.CharField(max_length=5)),
                ('BandwidthFWHM', models.DecimalField(decimal_places=6, max_digits=6)),
                ('BandwidthCorrected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpectralQuantity',
            fields=[
                ('value', models.CharField(max_length=13)),
                ('SpectralQKey', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionGeometry',
            fields=[
                ('value', models.CharField(max_length=5)),
                ('TranKey', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
