# Generated by Django 2.2.6 on 2019-11-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_header_element_fields_reflectiongeometry_spectral_data_spectral_distribution_fields_spectralquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectral_data',
            old_name='data_array_1',
            new_name='data_0',
        ),
        migrations.AddField(
            model_name='spectral_data',
            name='data_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='spectral_data',
            name='data_array_0',
            field=models.CharField(max_length=255),
        ),
    ]
