# Generated by Django 2.2.6 on 2019-11-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191102_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manu',
        ),
    ]
